version: "3"

services:
  autotests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GSpot
    environment:
      - GITHUB_TOKEN=${{ secrets.GIT_PARSER }}
      - GOOGLE_SHEETS_CREDENTIALS=${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
    volumes:
      - ./allure-results:/usr/project/allure-results