version: "3"

services:
  autotests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GSpot
    environment:
      - GITHUB_TOKEN==${GITHUB_TOKEN}
      - GOOGLE_SHEETS_CREDENTIALS=${GOOGLE_SHEETS_CREDENTIALS}
    volumes:
      - ./allure-results:/usr/project/allure-results