#name: Automation
#
#on:
#  pull_request:
#    branches:
#      - main
#    types:
#      - closed
#  schedule:
#    - cron: '0 10 * * 1'
#  workflow_dispatch:
#    inputs:
#      target:
#        description: 'Restart tests'
#        required: true
#        default: restart
#        type: choice
#        options:
#          - restart
#
#jobs:
#  Autotests:
#    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true || github.event_name == 'schedule'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Install Compose
#        uses: ndeloof/install-compose-action@v0.0.1
#        with:
#          version: v2.1.0 # defaults to 'latest'
#          legacy: true
#      - run: docker-compose --version
#
#      - name: Run tests
#        env:
#          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: docker-compose run autotests pytest --alluredir=allure-results ; allure generate allure-result --clean -o allure-report ; python -m source.matrix.update_autotests
#
#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
##       continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Build Allure report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        with:
#          allure_results: allure-results
#          allure_history: allure-history
#          keep_reports: 10
#          allure_report: allure_report
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
